language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - sys-img-x86-android-23
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-x86-android-23

script:
   - ./gradlew clean build connectedCheck test
